### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by grx123** [Danie1s/DNSPageView#1]
分别设置titleview和contentview的代理 有问题 contentview和titleview没有一起滚动

**Comment by Danie1s** [comment]
请问你是用哪个方式初始化？有参考demo中的代码吗？或者说是demo中出现的问题？

**Comment by grx123** [comment]
是把titleview加到nav上的

**Comment by grx123** [comment]
![2018-03-27 10 33 46](https://user-images.githubusercontent.com/10874922/37943556-9f60137c-31aa-11e8-9eca-088a04c508af.png)

**Comment by Danie1s** [comment]
你如果用pageViewManager初始化，就不需要进行delegate的设置，只需要设置titleView和contentView的位置和尺寸

**Comment by grx123** [comment]
问题是我现在要用到代理方法 怎么把他们两个关联到一起

**Comment by Danie1s** [comment]
pageViewManager已经把它们关联起来的，你说的要用到代理方法，是指什么？
