### ISSUE TITLE
老铁 标题为英文是lable背景是黑色的，

### ISSUE THREAD

**Issue by zhangchuanwei** [Danie1s/DNSPageView#13]

**Comment by chen7788** [comment]
我是用中，也遇到这个问题，title设置成英文或符号,lable背景为黑色

**Comment by chen7788** [comment]
或者把lable改为button就好了，而且button可以显示图片

**Comment by Danie1s** [comment]
已经更新

**Comment by gebenchao** [comment]
> 或者把lable改为button就好了，而且button可以显示图片

没啥效果啊。。

**Comment by gebenchao** [comment]
> 或者把lable改为button就好了，而且button可以显示图片

没有效果啊，背景还是黑色 尴尬了

**Comment by gebenchao** [comment]
> 已经更新
老铁 label英文的时候背景还是黑色，，

**Comment by Danie1s** [comment]
@gebenchao  你的版本是1.1.6？
