### ISSUE TITLE
频道较少时，切换频道会出现位置错乱

### ISSUE THREAD

**Issue by FerooJ** [Danie1s/DNSPageView#14]
DNSPageTitleView.swift文件，adjustLabelPosition 方法中设置scrollView的偏移量时，要先比较一下scrollView.contentSize.width 和 scrollView.bounds.width

还有一个小建议：
暴漏出来一个选中属性selectIndex，可以选中对应的label  （可能实现了我没注意到，\(^o^)/~）

**Comment by Danie1s** [comment]
感谢你提出的疑问和意见。
`style.isTitleViewScrollEnabled = true`，是用在title比较多的情况；
如果title比较少，则需要`style.isTitleViewScrollEnabled = false`，这时候title的宽带会平分titleView的总宽度，所以开发者可以根据不同的需求来设置

至于的建议，本来已经有`currentIndex`获取当前的index，也有`public func selectedTitle(inIndex index: Int)`实现手动选中
