### ISSUE TITLE
titleView很有主见，会自己滚动

### ISSUE THREAD

**Issue by whatsbug** [Danie1s/DNSPageView#15]
title个数比较少且isTitleViewScrollEnabled==true的情况下，点击title，titleView会自己滚动，设置isTitleViewScrollEnabled=false虽然不滚动了，但此时bottomLine的宽度是平分的，如何才可以不滚动且不是平分宽度
![kapture 2018-10-16 at 10 33 33](https://user-images.githubusercontent.com/7418617/46989501-e6c2e300-d12f-11e8-9147-330959448132.gif)

**Comment by Danie1s** [comment]
你说的没错，当isTitleViewScrollEnabled=false的时候，考虑的是title比较少的，所以平分titleView宽度，之前的风格都是这样的。
你的需求其实在项目demo的第四个样式里面实现了，就是手动计算titleView宽度

**Comment by whatsbug** [comment]
好的感谢，怪我没看全

**Comment by MYStrict** [comment]
问题描述：因为title的个数是不固定的，可能多可能少，在isTitleViewScrollEnabled=True的时候，title多的时候正常，少的时候偏移量出错，故而在adjustLabelPosition方法中的判断要优化，我这边自己加了一句if scrollView.contentSize.width < scrollView.bounds.width {  offsetX = 0 }，暂时解决了问题，但是我这边改的话就不能用cocoapods导入了

**Comment by Danie1s** [comment]
@MYStrict 谢谢你的建议，基于很多人都提出这个问题，所以我还是进行一下改动吧
