### ISSUE TITLE
第一个例子有个BUG,当标题设置在导航栏的时候...

### ISSUE THREAD

**Issue by boatt** [Danie1s/DNSPageView#16]
第一个例子有个BUG,当标题设置在导航栏的时候,如果我滑到第二个标签或者第三个标签的时候,点击进入该标签所打开的一个新的控制器,然后返回到当前页面,内容总是自动滚动到第一个标签页,但是标题还是指示着第二标签页

**Comment by Danie1s** [comment]
我按照你说的，进行一下测试，没发现问题。
你可以否提供一下代码？

**Comment by boatt** [comment]
![bug](https://user-images.githubusercontent.com/12237112/47491371-4bdbae80-d87d-11e8-848e-a47480cdbcd5.png)

**Comment by Danie1s** [comment]
哈哈，你画得很形象，但其实我明白你的意思，我自己测试是没问题，你最好提供代码让我看看，可以吗？

**Comment by change1wang73** [comment]
我这边在使用你的控件时，发现如果title传的不是中文，背景就变黑色了，调也没法调。。。你什么时候能处理下这个问题？
![image](https://user-images.githubusercontent.com/6769967/47699706-b199b300-dc4e-11e8-96ea-d198c41a8a21.png)

**Comment by Danie1s** [comment]
@change1wang73 
不好意思，这个bug我很早就已经修复了，麻烦你pod update一下，然后clean一下你的项目就可以了

**Comment by wisisimon** [comment]
> 哈哈，你画得很形象，但其实我明白你的意思，我自己测试是没问题，你最好提供代码让我看看，可以吗？

我也有同样困恼

**Comment by Danie1s** [comment]
@wisisimon 
我再次测试了，也并没有发现任何问题，你们在viewDidAppear初始化吗？
能否提供demo？

**Comment by nsuxin** [comment]
目测是iOS12.1的bug，目前还在看

**Comment by Smilestep** [comment]
![1542254007504](https://user-images.githubusercontent.com/10706559/48529225-1b5fc100-e8cd-11e8-8922-f5254e960da2.jpg)
![1542253928960](https://user-images.githubusercontent.com/10706559/48529235-231f6580-e8cd-11e8-9520-e9358d34f52a.jpg)
@Danie1s 我遇到滑动到第二或者第三个标签，然后滑动tableview回调一个参数出去父VC的时候，就出现容器跳回到第一个标签到容器

**Comment by nsuxin** [comment]
iOS12.1有个bug，当push进页面再返回来时，会走到contentView的layoutSubviews方法，方法里的`layout.offset = CGFloat(startIndex) * bounds.size.width`这行会导致contentView的contentOffset重置到startIndex的位置。亲测12.0以及12.1.1系统无此问题。

**Comment by Danie1s** [comment]
@nsuxin 谢谢你的测试
每次有人跟我提这个bug，我都有去测试，目前用了iPhone XS Max和iPhone 6s进行测试，都是iOS 12.1，并没有发现问题
我是在demo里面，`ContentViewController`加上
```swift
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        let controller = UIViewController()
        controller.view.backgroundColor = UIColor.white
        navigationController?.pushViewController(controller, animated: true)
    }
```
四种样式都测试，没有发现问题
你可以提供一下有问题的demo吗？

**Comment by nsuxin** [comment]
> @nsuxin 谢谢你的测试
> 每次有人跟我提这个bug，我都有去测试，目前用了iPhone XS Max和iPhone 6s进行测试，都是iOS 12.1，并没有发现问题
> 我是在demo里面，`ContentViewController`加上
> 
> ```swift
>     override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
>         let controller = UIViewController()
>         controller.view.backgroundColor = UIColor.white
>         navigationController?.pushViewController(controller, animated: true)
>     }
> ```
> 
> 四种样式都测试，没有发现问题
> 你可以提供一下有问题的demo吗？

找到重现步骤了，`UINavigationController` + `UITabBarController`，可能跟这个有关，关联问题：[https://github.com/ChenYilong/iOS12AdaptationTips/issues/3](url)

**Comment by Danie1s** [comment]
已经更新
