### ISSUE TITLE
提点意见吧，感觉比较致命

### ISSUE THREAD

**Issue by ZHANGKAILUN1108** [Danie1s/DNSPageView#19]
不知道题主在编写的时候有没有考虑到childview的监听问题，仅仅提供了几个无关紧要的代理方法还说是常见，举个例子，我想在子视图做通用UI配置，这样的必定index不同的页面可能UI也不会相同，需要根据下角标或者其他值进行UI设定，当我想在contentview中监听到当前Index是多少的时候，无法办到，而且很麻烦的要从父控制器进行回调，UI感觉不是很重要，往往是这种实际触碰到业务逻辑的时候让人觉得很致命，因为你没法很自由的去做一些逻辑。

**Comment by Danie1s** [comment]
感谢您提出的意见。UI类型的库本来就很难满足所有人的需求，我只是把我开发中遇到的最常见的使用需求考虑进去了，也把很多东西暴露出来了，使用者可以根据自己的需求进行使用。您所说的需求，只需在初始化的时候，把`index`传到contentView就可以了。还是说您需要所有childview都要实时得到当前的index？回调、KVO、通知都可以，不过正常来说，不是只需要显示的childview知道当前的index就可以吗？如果您还有什么不明白的地方，欢迎提问

**Comment by ZHANGKAILUN1108** [comment]
好的，我觉得在childview中可以多设置几个代理方法，包括生命周期之类的添加到childview的代理方法中最好，然后带入index，这样可以更自由的控制一些UI的显示，刷新。

**Comment by Danie1s** [comment]
一般是在父controller初始化DNSPageView，contentView里面的childview是用子控制器来布局，初始化的时候可以把index传进去，而这些子控制器本来就是由开发者自己生成的，里面本来就是有生命周期之类的方法，请参考demo
