### ISSUE TITLE
关于demo中，vc3中不设置automaticallyAdjustsScrollViewInsets=false崩溃问题

### ISSUE THREAD

**Issue by objcxiaobai** [Danie1s/DNSPageView#21]

**Comment by Danie1s** [comment]
我找到问题了，由于是基于`UIScrollView`实现，那么就无法避免它的一些特性，问题已经解决，但引发了另外一个问题。
`navigationBar.isTranslucent = true`的时候，布局是从（0, 0）开始的，所以默认系统会给`UIScrollView`添加offset，iOS 11 以前就是`automaticallyAdjustsScrollViewInsets `起作用，iOS 11以后引入SafeArea，由`contentInsetAdjustmentBehavior`管理
`contentView`用`UICollectionView`实现，所以这个特性会让`UICollectionView`的height小于`item`的高度，造成奇怪的bug
为什么其他例子中底部没有添加offset，这个我也不清楚，可能是系统的bug
所以你最好要了解自己需要的布局效果是怎么样，我会尽快更新

**Comment by objcxiaobai** [comment]
布局效果，就是让导航栏作为分段菜单（目前只知道这个方法，不知道有木有更好的方法），跟作者v3类似。
所以我用edgesForExtendedLayout = UIRectEdge.all;
navigationController?.navigationBar.isTranslucent = false;
替换了automaticallyAdjustsScrollViewInsets
实现了我想要的效果。
