### ISSUE TITLE
怎么重新加载dnspageview？

### ISSUE THREAD

**Issue by slash130** [Danie1s/DNSPageView#22]
我用了一个频道编辑的插件，现在遇到个问题，在频道编辑里添加或删除title后退出编辑界面，返回控制器后怎么刷新dnspageview？我在编辑退出时将新的title数组存入UserDefaults，希望回到dnspageview时titleview显示对应的数组。

**Comment by Danie1s** [comment]
我大概明白你的需求，DNSPageView设计的时候没有考虑你这种频繁刷新的需求，所以没有刷新的功能，
但是还是有办法实现的。
你有title数组，就可以重新创建DNSPageView来达到刷新的效果，需要注意的时候，要把原来的childViewControllers保留下来，如果删除title，就删除对应的vc，如果增加title，就添加对应的vc。这样原来存在的页面就会保持不变
