### ISSUE TITLE
请问下可以设置 titleView bottomBar 的长度和文字居中

### ISSUE THREAD

**Issue by weitieda** [Danie1s/DNSPageView#23]
大佬好，

能否实现如图的效果，比如有3个tab，bar的宽度就是屏幕宽度/3，然后tab的文字部分居中。`style.isTitleViewScrollEnabled = false` 不需要滑动

恕小弟学浅，看到 demo4 中有类似的设置，但没弄明白。。

谢谢大佬指点

![xnip2019-02-26_18-15-11](https://user-images.githubusercontent.com/35972055/53453562-7a67c280-39f2-11e9-8df8-0ecfedf2fb4e.jpg)

**Comment by Danie1s** [comment]
设置`style.isTitleViewScrollEnabled = false`即可
