### ISSUE TITLE
滑动切换时childViewController代码里的viewWillDisappear执行异常

### ISSUE THREAD

**Issue by slash130** [Danie1s/DNSPageView#24]
我这部分childViewController需要在离开控制器时执行命令，我用的viewWillDisappear，结果滑动切换时有时会执行命令有时不执行命令，点击titleview里的标签切换时没问题。

**Comment by Danie1s** [comment]
`contentView`是用`collectionView`实现的，`collectionView`是有复用cell的机制，点击titleview切换的话，可以直接复用当前cell，所以会执行`viewWillDisappear`，而滑动切换，由于界面上需要显示两个cell，所以当切换到第三个`childViewController` 时，才会复用第一个cell，这时候才执行第一个`childViewController`的`viewWillDisappear`。

关于你的需求，我会新增一些代理方法，请稍等

**Comment by Danie1s** [comment]
已经更新

**Comment by slash130** [comment]
谢谢啦！
