### ISSUE TITLE
使用说明里的一个问题

### ISSUE THREAD

**Issue by littlepriest** [Danie1s/DNSPageView#26]
标签下划线的宽度跟随文字的宽度

当style.isTitleViewScrollEnabled = false时，表示标签比较少，默认每个标签平分整个titleView的宽度，而下划线的宽度等于标签的宽度，这种样式的需求也很常见。

**要想实现标签下划线的宽度跟随文字的宽度，需要设置style.isTitleViewScrollEnabled = true，可以参考demo中的第四种样式。**

加粗这句，不知道是有误还是什么，我稍微看了一下源码，只要设置style.isBottomLineAutoWidth = true就行了

**Comment by Danie1s** [comment]
你好，应该没有`isBottomLineAutoWidth `这个属性

`style.isTitleViewScrollEnabled = true`，本来的作用是当标签比较多，让titleView可以滑动，随着而来就多了一个效果，标签下划线的宽度跟随文字的宽度

**Comment by littlepriest** [comment]
public var isBottomLineAutoWidth = false //2018年06月27日添加,开启后下划线自动适配文字长度

我直接pod安装的版本，是有这个东西的。 第47行

**Comment by Danie1s** [comment]
那我不清楚，我记得没有添加过这个属性，目前最新的版本是1.1.5，如果你使用的不是，麻烦你使用`pod update`更新一下
