### ISSUE TITLE
当我想进入push下一个页面的时候，没有效果。

### ISSUE THREAD

**Issue by objcxiaobai** [Danie1s/DNSPageView#29]
现在都在子控制器上，当我想进下一个页面，想查看详细信息
  self.navigationController?.pushViewController(Show, animated: true);
没有效果。

使用        self.present(Show, animated: true, completion: nil)
是进行跳转了，但是。标题导航还存在

更新：好像明白了，用个代理交给父控制器去跳转就行了。
希望作者文档标注一下～

**Comment by Danie1s** [comment]
需要把子控制器添加到父控制器里才可以对子控制器进行push等操作，麻烦参考demo
```swift
        for i in 0..<titles.count {
            let controller = ContentViewController()
            controller.view.backgroundColor = UIColor.randomColor
            controller.index = i
            addChild(controller)
        }
```

**Comment by objcxiaobai** [comment]
NSPageViewManager(style: style, titles: title, childViewControllers: Controllers); 
 请问这句代码？算是添加的父控制器里么 ？

**Comment by Danie1s** [comment]
`addChild(controller)`
