### ISSUE TITLE
请教下如何实现进入页面后直接显示指定的VC

### ISSUE THREAD

**Issue by a1259667899** [Danie1s/DNSPageView#3]
比如childViewControllers总共有10个，进入页面的时候只想让它直接显示第5个，其他的childViewcontroller不加载，等到滑动到位置的时候再加载，我一直没有思路

**Comment by Danie1s** [comment]
我这个库已经支持这个需求，可以参考demo。至于如何实现的话，是通过自定义UICollectionViewFlowLayout，重写prepare方法，在里面设置collectionView的偏移量，详细的你可以看看代码
