### ISSUE TITLE
set bottom line width ?

### ISSUE THREAD

**Issue by nilhy** [Danie1s/DNSPageView#32]
####  RT，能不能提供在 isTitleViewScrollEnabled = false  的情况下；

bottom line 的宽度自定义某个值？ 

#### 原因
当标签少的时候，其实不需要那么宽的bottom line ，有点难看。有什么快捷的方法，指定吗？

**Comment by Danie1s** [comment]
设置`isTitleViewScrollEnabled = true`，可以让下划线跟文字一样宽，这样能足你的需求吗？

**Comment by nilhy** [comment]
@Danie1s  表示无法满足

![](https://blog-resources-1256752477.cos.ap-guangzhou.myqcloud.com/images20190801094945.png)

**Comment by Danie1s** [comment]
![image](https://user-images.githubusercontent.com/19432029/62260645-43845580-b445-11e9-9cc0-a9c37f28bda0.png)
这样可以吗？

**Comment by nilhy** [comment]
@Danie1s  目前而言，我已经按照这种方式写了，isTitleViewScrollEnabled == true  然后宽度自己算的，但是感觉还是无法解决这种需求的存在 (泪奔...)

**Comment by Danie1s** [comment]
我截图那个能满足你需求？

**Comment by nilhy** [comment]
不能啊， 只能将就着。要不就只能自定义

**Comment by shyh5** [comment]
宽度能设置个固定值，不跟着每个title的宽度一样吗。

**Comment by Danie1s** [comment]
@shyh5 @nilhy 
我找个时间更新一下吧

**Comment by shyh5** [comment]
@Danie1s  谢谢大大，麻烦了

**Comment by Danie1s** [comment]
已经更新
