### ISSUE TITLE
isTitleScaleEnabled

### ISSUE THREAD

**Issue by vayneee** [Danie1s/DNSPageView#33]
isTitleScaleEnabled = true 的时候，currentIndex的那个标题的文字会显示不完整，我看了一下是因为label的width变小了。

**Comment by Danie1s** [comment]
请问你是什么情况下出现的，我自己测试不会

![image](https://user-images.githubusercontent.com/19432029/62796573-2d912780-bb0c-11e9-8c04-f3013616a279.png)

![image](https://user-images.githubusercontent.com/19432029/62796600-33870880-bb0c-11e9-9e3e-465a042632e7.png)
第二张图的情况是标题实在太长，同时缩放系数太大，这个需要开发者自己考虑

**Comment by vayneee** [comment]
这个是demo，viewcontroller2里的，红色框里的代码是我做的修改。 
![Snip20190810_1](https://user-images.githubusercontent.com/17397356/62815624-a95f9400-bb4d-11e9-808d-a3253b478438.png)
![Snip20190810_2](https://user-images.githubusercontent.com/17397356/62815626-acf31b00-bb4d-11e9-9474-996f278e9ee7.png)

我也很纳闷了。我有两个vc都是storyboard，一个正常一个不正常，然后我就把demo也改了一下。发现demo也异常。

**Comment by Danie1s** [comment]
好的，我已经发现问题了，很快就会更新，谢谢你的测试

**Comment by Danie1s** [comment]
@vayneee 你的截图好像比较漂亮，带阴影，请问是什么软件？

**Comment by vayneee** [comment]
Snip  挺好用的

**Comment by ynpl** [comment]
我觉得Mac 截图Xnip 最好用  ..
