### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by suyinkaishifangle** [Danie1s/DNSPageView#34]
我本以为是自己代码出问题了后面新建了一个项目只pod了 'DNSPageView' ，仍然会出现这个错误

**Comment by Danie1s** [comment]
兄弟，你能先说说你怎么操作吗？用Demo试试有没有问题？

**Comment by suyinkaishifangle** [comment]
我新建了一个项目  然后在只添加了DNSPageView这个的第三方库  直接运行  也要报着个错，我今天再试试

**Comment by suyinkaishifangle** [comment]
第一次pull项目里的代码用模拟器能运行，后面自己更新了代码后，模拟器死活运行不起来，提示****.framework: bundle format unrecognized, invalid, or unsuitable 说是第三库没找到的意思，于是去该路径下找到 “/Users/用户名/Library/Developer/Xcode/DerivedData“ （注意用户名是自己电脑用户） DerivedData 文件夹直接删除，然后打开终端执行pod install，执行完毕，clean一下，成功运行

但是只是这个库出现这个问题，刚开始我只移除这个库，就可以正常运行，可能是自己操作问题，感谢作者花时间回答问题，也感谢作者的贡献。

**Comment by Danie1s** [comment]
恩，我试了一下是没问题的
