### ISSUE TITLE
情景：数据源字数不同时 下划线位置偏移

### ISSUE THREAD

**Issue by huangpu0** [Danie1s/DNSPageView#35]
点击会偏移 滑动有问题 如图示
![IMG_1274](https://user-images.githubusercontent.com/18637612/65003872-f3961b00-d92c-11e9-9eeb-27b3bd2876aa.JPG)

**Comment by Danie1s** [comment]
麻烦先更新到最新版试试

**Comment by huangpu0** [comment]
1.2.0 最新的  demo

**Comment by Danie1s** [comment]
已经更新
