### ISSUE TITLE
背景颜色，如图

### ISSUE THREAD

**Issue by liuxinghudiejie** [Danie1s/DNSPageView#38]
您好，我不知道这个是我哪里设置不对，还是bug，如图，中文显示正常，英文的背景就是黑色的，swift5，最新版本的DNSPageView
<img width="372" alt="46E5A295-08A5-4778-BBC1-E82DC397FF59" src="https://user-images.githubusercontent.com/14884778/69527745-e8541100-0fa7-11ea-8779-a9df3299b131.png">

**Comment by Danie1s** [comment]
试试`pod update`

**Comment by liuxinghudiejie** [comment]
ok,最新版问题解决
