### ISSUE TITLE
停止滚动监听的问题

### ISSUE THREAD

**Issue by slash130** [Danie1s/DNSPageView#39]
我在回调里的停止滚动监听中执行mj的下拉刷新，当页面滚动切换时滑动页面但是不完全离开当前页面抬起手指后页面回弹回来也会触发contentViewDidEndScroll，我希望这种操作没离开当前页面时不触发监听。这个问题在左右两侧最边上的页是最明显的，最左侧页面向右滑动就会触发监听，最右侧的页面也是如此。

**Comment by Danie1s** [comment]
`contentViewDidEndScroll` ，就如这个方法名一样，滚动结束就会调用，这是没问题的

而你需要的效果应该用其他方式来实现，例如： `viewDidAppear`

**Comment by slash130** [comment]
我试了viewDidAppear，不过效果不太好，当滑动当前页面时下一个页面刚出来一点就执行下拉刷新了而不是滑到下一个页面停下来之后再执行。

**Comment by Danie1s** [comment]
兄弟，那你再加一个变量，在 `contentViewDidEndScroll` 中处理不就好了吗？这是你开发的事情，我觉得不应该是我来教你

**Comment by slash130** [comment]
不好意思，新手开发有时遇到的问题没想明白，见笑了。
