### ISSUE TITLE
当titles的个数很少的时候，滑动时title所在的view发生偏移

### ISSUE THREAD

**Issue by chouchang** [Danie1s/DNSPageView#4]
问题如图，在demo中可以复现。
![wechatimg38](https://user-images.githubusercontent.com/10349316/39611034-f9d137ba-4f86-11e8-913c-a66ab6127e2b.jpeg)

**Comment by Danie1s** [comment]
@chouchang 你说得对，当**style.isTitleScrollEnable = true**时，titleLabel的宽度是文字的宽度 + titleMargin，所以如果这个时候titles的个数很少的时候，就没有占满整个titleView。
实际上titles的个数很少的时候，titleView就不需要滑动了，此时设置**style.isTitleScrollEnable = false**，即可解决。
