### ISSUE TITLE
features

### ISSUE THREAD

**Issue by nilhy** [Danie1s/DNSPageView#40]
1. 能否添加一个选中时候的字体? (项目需求中, 选中的item字体会进行一个加粗)
2. titleView 左右的间距调整, 即使填充整个屏幕高度, 但是可以改变 title view content inset ,这样处理起来会更方便

**Comment by Danie1s** [comment]
1.  我找个时间添加这个功能吧
2.  `style.titleMargin` 应该可以满足你的需求

**Comment by Danie1s** [comment]
@nilhy 已经更新

**Comment by nilhy** [comment]
可能需要再调整一下, 字体如果改变,  label 的size 不够, 会变成省略成`....` 能否加一个item 的edge inset呢 ? 或者给定一个修复width 如果有传那就额外增加一定的宽度
<img width="439" alt="截屏2020-05-15下午4 24 46" src="https://user-images.githubusercontent.com/20027844/82031481-88276780-96cc-11ea-86ba-f43ada6ba9ba.png">

**Comment by nilhy** [comment]
麻烦了. 谢谢大佬

**Comment by Danie1s** [comment]
更新了
