### ISSUE TITLE
换成四个字的，显示就变成...了

### ISSUE THREAD

**Issue by xiaopindev** [Danie1s/DNSPageView#42]
let titles = ["头条", "视频", "娱乐娱乐", "要问", "体育" , "科技" , "汽车" , "时尚" , "图片" , "游戏" , "房产"]

能不能适配一下大于两个字以上的情况？

**Comment by Danie1s** [comment]
![image](https://user-images.githubusercontent.com/19432029/83005327-3de6a480-a043-11ea-83d1-40e803cee488.png)

**Comment by xiaopindev** [comment]
好的，辛苦！
