### ISSUE TITLE
切换缩放的时候，会变成：文字+点点点

### ISSUE THREAD

**Issue by xiaopindev** [Danie1s/DNSPageView#44]
let titles = ["头条", "视频", "娱乐娱乐", "要问", "体育" , "科技" , "汽车" , "时尚" , "图片" , "游戏" , "房产"]
很多时候滑动缩放的时候，会变成：文字+点点点，2个字 的也会出现

![WX20200607-142125](https://user-images.githubusercontent.com/2084285/83961882-35575f00-a8ca-11ea-8718-422210bc6732.png)

**Comment by Danie1s** [comment]
#42

**Comment by Danie1s** [comment]
Duplicate of #42
