### ISSUE TITLE
有没有对暗黑模式有所适配？

### ISSUE THREAD

**Issue by huyabin** [Danie1s/DNSPageView#45]
作者您好。iOS13的暗黑模式有需求得切换，是否可以像swiftTheem一样整个暗黑模式方便适配一下？

**Comment by Danie1s** [comment]
可以，等待我更新

**Comment by Danie1s** [comment]
已更新

**Comment by huyabin** [comment]
您好像误解了我的意思。。我的意思是如果切换暗黑模式titleView的背景色和文字的高亮色及未点击的颜色进行切换。
