### ISSUE TITLE
动态改变title值问题

### ISSUE THREAD

**Issue by xiaopindev** [Danie1s/DNSPageView#49]
代码
` let titles = ["即时","赛果","赛程","关注"]
        let vc1 = vc1()
        addChild(vc1)
        let vc2 = vc2()
        addChild(vc2)
        let vc3 = vc3()
        addChild(vc3)
        let vc4 = vc4()
        addChild(vc4)

        titleView = PageTitleView(frame: pp_frame(5,88, 375 ,30), style: style, titles: titles, currentIndex: 0)

        contentView = PageContentView(frame: pp_frame(0,88,375,500), style: style, childViewControllers: children, currentIndex: 0)

        view.addSubview(titleView!)
        view.addSubview(contentView!)

        titleView?.delegate = contentView
        contentView?.delegate = titleView`
        
我想要动态修改title的值：
` let label = self.titleView?.titleLabels[3]
        label?.text = "关注(12)"`

问题：关注 显示变成 “关...” , 显示不全，能动态改变值又能正常显示吗？

**Comment by Danie1s** [comment]
抱歉，当初设计的时候没有考虑到动态修改title的值，我最近会增加这个特性，请耐心等待

**Comment by Danie1s** [comment]
@xiaopindev 已经更新

**Comment by xiaopindev** [comment]
> @xiaopindev 已经更新

好的， 我试试，感谢更新！

**Comment by xiaopindev** [comment]
> @xiaopindev 已经更新

你用的PageViewManager， 我没有用这种方式也可以吗？

**Comment by xiaopindev** [comment]
> @xiaopindev 已经更新

有方法可以直接用，你设置成私有的和内部访问了

**Comment by Danie1s** [comment]
不行，为了代码更加内聚，请使用我提供的方法
