### ISSUE TITLE
title滚动时颜色变化问题

### ISSUE THREAD

**Issue by lx1992lx** [Danie1s/DNSPageView#50]
我发现PageView在滚动时，目标文本会发生变化，而且sourceLabel颜色在取消滚动后无法恢复之前的颜色
关键代码在PageTitleView的404-409行，去掉这些代码就好了
sourceLabel.textColor = UIColor((selectRGB.red - progress * deltaRGB.red,
                                         selectRGB.green - progress * deltaRGB.green,
                                         selectRGB.blue - progress * deltaRGB.blue))
  targetLabel.textColor = UIColor((normalRGB.red + progress * deltaRGB.red,
                                         normalRGB.green + progress * deltaRGB.green,
                                         normalRGB.blue + progress * deltaRGB.blue))

**Comment by Danie1s** [comment]
兄弟，我没看明白你的意思是什么，这里要的就是 sourceLabel 和 targetLabel 的 title 在滚动的时候颜色会渐变

**Comment by lx1992lx** [comment]
我发现在渐变的时候，在模拟器中颜色会出现混乱的情况，比如标签A->B，当我滚动A还没有到B的位置的时候，B已经变色，这时如果我松手，选中状态回滚到A，A和B标签都已经变成选中颜色了

**Comment by Danie1s** [comment]
但是我没有测试到你说的这种情况，也没人其他提出这个问题，麻烦你用最新版试试，或者用demo试试

**Comment by xXuteng** [comment]
我刚刚也发现了这个问题，A->B，就是左滑或者右滑一点点，只滑一点点，不能滑多了，B也被选中了，但是A还没滑过去，A也是选中状态，你有邮箱吗？邮箱多少？我可以把这个录个视频发你一下
