### ISSUE TITLE
请问如何在PageViewController 页面 监听page滚动到哪个页面了 

### ISSUE THREAD

**Issue by hjqiaho** [Danie1s/DNSPageView#51]
需要根据当前页面在父viewController 显示不同的控件

**Comment by hjqiaho** [comment]
看到了 PageContentViewDelegate

pageViewManager.contentView.delegate = self

**Comment by hjqiaho** [comment]
发现这个delegate和需求的貌似有点差别
这个是用来关联title和congtent的
        self.titleView.delegate = self.contentView
        self.contentView.delegate = self.titleView
如果更改了这个就会影响标题内容切换同步

需求是不管点标题切换 还是滑动切换 都有个回调给pageviewController  （不是回调给childViewControllers）
因为要在page 监听当前页面 处理外面页面的一些问题

**Comment by Danie1s** [comment]
在childViewControllers回调给外界不就好了吗？
