### ISSUE TITLE
当页面在第一页的时候 ，苹果系统的侧滑返回上一页事件失效了

### ISSUE THREAD

**Issue by hjqiaho** [Danie1s/DNSPageView#52]
contentView  位置从左侧划返回上一页的系统事件失效了

**Comment by Danie1s** [comment]
并不会，你可以使用demo进行尝试。该手势失效是因为你对左上角的item进行了设置，百度一下解决的方法

**Comment by hjqiaho** [comment]
[http://fs.iclass30.com/Android/test/QQ20201104-141935-HD.mp4](url)

不是设置的问题  如果我设置了一个边距 它就能正常使用
![image](https://user-images.githubusercontent.com/10189815/98076587-7bc8de00-1ea9-11eb-87bd-f5fc56c58dca.png)
还是没研究明白哪里冲突造成的

**Comment by hjqiaho** [comment]
extension UICollectionView:UIGestureRecognizerDelegate{
    public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRequireFailureOf otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        if gestureRecognizer.view == self {
                if self.contentOffset.x <= 0 {
                    let translatedPoint = otherGestureRecognizer.location(in: self)
                    if translatedPoint.x <= 20 {
                        return true

                    }
                }
            }
        return false
    }
}
