### ISSUE TITLE
当titleSelectedFont大于titleFont时，会变成...，显示不全

### ISSUE THREAD

**Issue by lihj** [Danie1s/DNSPageView#53]
style.titleFont = UIFont.systemFont(ofSize: 14)
        style.titleSelectedFont = UIFont.systemFont(ofSize: 15)
        style.isShowCoverView = true
        style.isTitleViewScrollEnabled = true

我style这样设置时，遮罩选中文字会变成...

**Comment by Danie1s** [comment]
这种情况需要添加 titleInset，例如：
`style.titleInset = 10`

**Comment by lihj** [comment]
谢谢大佬

**Comment by lihj** [comment]
> 这种情况需要添加 titleInset，例如：
> `style.titleInset = 10`

谢谢大佬
