### ISSUE TITLE
Thread 1: Assertion failed: currentIndex < 0 or currentIndex >= titles.count

### ISSUE THREAD

**Issue by lihj** [Danie1s/DNSPageView#59]
比如原来有5个，新的数组才1个，使用            pageViewManager.configure(titles: titles, childViewControllers: self.children, style: style)
会闪退，currentIndex 没复位，造成越界问题

**Comment by Danie1s** [comment]
默认是不复位的，因为我不知道数据改变后，外界希望显示哪一页

你可以先通过 `public func selectedTitle(at index: Int, animated: Bool = true)` 来改变 currentIndex ，再更新数据
