### ISSUE TITLE
您好～我的contentView present ViewController frame跑掉

### ISSUE THREAD

**Issue by wisisimon** [Danie1s/DNSPageView#6]
我的titleView在navigationBar，當我contentView present ViewController 然後dismiss，原本的contentView的y軸卡進navigationBar，請問大大可否協助幫忙，謝謝。

![2018-07-30 5 46 37](https://user-images.githubusercontent.com/10337181/43390341-8af4f852-9420-11e8-823d-95a227872634.png)

**Comment by wisisimon** [comment]
當我present 的時候 navigationBar會突然不見一下。
在viewDidLayoutSubView 原本frame是(0.0, 0.0, 414.0, 672.0)
dismiss後變成(0.0, 0.0, 414.0, 736.0)，相差64的高度。

**Comment by Danie1s** [comment]
这是适配的问题。
如果是iOS 11或以上：
`scrollView.contentInsetAdjustmentBehavior = .never`
否则：
`automaticallyAdjustsScrollViewInsets = false`
